"""create sample items

Revision ID: 20260802_0002
Revises: 20260418_0001
Create Date: 2026-08-02 23:10:57.036254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '20260802_0002'
down_revision: Union[str, Sequence[str], None] = '20260418_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sample_items', sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('owner_user_id', sa.Uuid(), nullable=False),
        sa.Column('title', sa.String(length=120), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'],
                                name=op.f('fk_sample_items_owner_user_id_users'),
                                ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_sample_items')))
    op.create_index(op.f('ix_sample_items_owner_user_id'),
                    'sample_items', ['owner_user_id'],
                    unique=False)
    op.create_index('ix_sample_items_owner_user_id_created_at_id',
                    'sample_items', ['owner_user_id', 'created_at', 'id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sample_items_owner_user_id_created_at_id', table_name='sample_items')
    op.drop_index(op.f('ix_sample_items_owner_user_id'), table_name='sample_items')
    op.drop_table('sample_items')
    # ### end Alembic commands ###
